# Generated by Django 5.2.8 on 2025-11-26 11:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainAnchor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('evidence_hash', models.CharField(db_index=True, max_length=64)),
                ('ipfs_cid', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('block_number', models.IntegerField(blank=True, null=True)),
                ('confirmations', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('network', models.CharField(default='preview', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['report_id'], name='blockchain__report__a0d17d_idx'), models.Index(fields=['evidence_hash'], name='blockchain__evidenc_abb0da_idx'), models.Index(fields=['status'], name='blockchain__status_b1960c_idx'), models.Index(fields=['transaction_hash'], name='blockchain__transac_718b74_idx')],
            },
        ),
    ]
