# Generated by Django 5.2.8 on 2025-11-21 12:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('resource', models.CharField(max_length=100)),
                ('details', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_code', models.CharField(editable=False, max_length=20, unique=True)),
                ('category', models.CharField(choices=[('theft', 'Theft'), ('kidnapping', 'Kidnapping'), ('corruption', 'Corruption'), ('house_fire', 'House Fire'), ('road_accident', 'Road Accident'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('location_description', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('reporter_name', models.CharField(blank=True, max_length=100)),
                ('reporter_phone', models.CharField(blank=True, max_length=15)),
                ('reporter_email', models.EmailField(blank=True, max_length=254)),
                ('media_file', models.FileField(blank=True, null=True, upload_to='reports/media/')),
                ('media_thumbnail', models.ImageField(blank=True, null=True, upload_to='reports/thumbnails/')),
                ('ipfs_cid', models.CharField(blank=True, max_length=100)),
                ('evidence_json_cid', models.CharField(blank=True, max_length=100)),
                ('evidence_hash', models.CharField(blank=True, max_length=64)),
                ('transaction_hash', models.CharField(blank=True, max_length=64)),
                ('is_hash_anchored', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_review', 'In Review'), ('forwarded', 'Forwarded'), ('actioned', 'Actioned'), ('closed', 'Closed')], default='new', max_length=20)),
                ('priority', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('new', 'New'), ('in_review', 'In Review'), ('forwarded', 'Forwarded'), ('actioned', 'Actioned'), ('closed', 'Closed')], max_length=20)),
                ('new_status', models.CharField(choices=[('new', 'New'), ('in_review', 'In Review'), ('forwarded', 'Forwarded'), ('actioned', 'Actioned'), ('closed', 'Closed')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='reports.report')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
