# Generated by Django 5.2.8 on 2025-11-22 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='device_info',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='report',
            name='blockchain_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='report',
            name='verified_on_chain',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reportupdate',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['reference_code'], name='reports_rep_referen_469f66_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['category'], name='reports_rep_categor_b7680f_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status'], name='reports_rep_status_c732ef_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['created_at'], name='reports_rep_created_a6aabf_idx'),
        ),
    ]
