# Generated by Django 5.2.8 on 2025-11-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auditlog_device_info_report_blockchain_metadata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='evidence_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='evidence_json_cid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='ipfs_cid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='reporter_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='report',
            name='reporter_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='reporter_phone',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='report',
            name='transaction_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
