# Generated by Django 5.2.8 on 2025-11-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_report_evidence_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='location_description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
