# Generated by Django 5.2.8 on 2025-11-29 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_report_location_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='ipfs_report_cid',
            field=models.CharField(blank=True, help_text='IPFS CID for complete report (distributed across 1000+ nodes)', max_length=100, null=True),
        ),
    ]
